### ISSUE TITLE
100% CPU utilization

### ISSUE THREAD

**Issue by Teumer** [sexibytes/sexilog#36]
There's about 10-30 of these processes: /usr/lib/jvm/java-7-openjdk-amd64 and even now with 3 vCores it's been at 100% CPU usage for over 48 hours now. I've restarted sexilog and the issue remains.
![sexilog_github](https://cloud.githubusercontent.com/assets/8092150/8120081/f41bb93e-1060-11e5-9780-519151f46ff1.PNG)

**Comment by rschitz** [comment]
could you check if there is space on /sexilog ?

**Comment by Teumer** [comment]
100% drive use on /sexilog. I've cleared old logs and drive use is now at 29%. However, CPU usage is still high.

**Comment by rschitz** [comment]
one index could have been corrupted, you should remove the current index too
